CREATE TYPE "TransactionSource" AS ENUM ('USER', 'AI', 'RECURRING', 'WALLET_INITIAL_BALANCE', 'WALLET_ADJUSTMENT');

ALTER TABLE "Transaction" ADD COLUMN "source" "TransactionSource" NOT NULL DEFAULT 'USER';

ALTER TABLE "Wallet" ADD COLUMN "isArchived" BOOLEAN NOT NULL DEFAULT false;
